name: "Auto Guest Login"
description: "A web server that provides an easy way for guests to get access to Home Assistant"
version: "0.0.1"
slug: "ha-auto-guest-login"
init: false
image: "norick/image-{arch}-ha-auto-guest-login-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: default
ports:
  80/tcp: 8675

options:
  guest_username:
  guest_password:
  guest_dashboard_path: lovelace/default_view

schema:
  guest_username: str
  guest_password: password
  guest_dashboard_path: str