name: "Guest Login"
description: "A web server that provides an easy way for guests to get access to Home Assistant"
version: "0.0.1"
slug: "ha-guest-login"
init: false
image: "norick/image-{arch}-ha-guest-login-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: 8675