name: "Home Assistant Addon Test Build"

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --docker-hub norick/ha-guest-login-addon
