name: "Home Assistant Addon Build and Publish"

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run build and publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ha-auto-guest-login \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}
